storage-capacity-per-user: 2000000
max-notes-per-user: 30
max-note-file-size: 10000
max-characters-per-line: 300
filename-max-characters: 30

max-notes-in-memory: 8
max-notes-in-memory-per-player: 2

use-character-whitelist: true
whitelisted-characters: [' ', '!', '#', '$', '%', '&', '''', '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\',']','^','_','`','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~','∞']
