name: Notepad
version: "1.2.0-alpha"
main: com.opencratesoftware.mcnotepad.Notepad
api-version: 1.14
commands:
  notepad:
    description: "Manage notes or lists for any purpose"
    usage:
    aliases: ["notes", "note"]